### ISSUE TITLE
Не работает добавление пользователя по id или имени пользователя

### ISSUE THREAD

**Issue by disovi** [rand0mm/vk-vue#2]
1. Не работает добавление пользователя по id или имени пользователя
2. При вводе имени часто либо ничего не отображается, либо возникает такая ошибка

![image](https://user-images.githubusercontent.com/705617/197228596-46b15c09-0305-4e69-8192-77424c5ae294.png)

https://user-images.githubusercontent.com/705617/197229086-91e6642b-42ad-4031-8599-dc4301fa5968.mp4

помогает снятие/возвращание фокуса на селект

3. Поскольку ключ зашит в программе - выборка в автодополнении нерепрезентативна и отображаются только первые 10 пользователей, что не даёт возможности найти нужного

**Comment by disovi** [comment]
скролл появился, но результатов по-прежнему 10

**Comment by rand0mm** [comment]
да, не убрал ограничение,пофиксил)
