### ISSUE TITLE
Отсутствует отображение пола, возраста, количества друзей в карточке друга

### ISSUE THREAD

**Issue by disovi** [rand0mm/vk-vue#4]
![image](https://user-images.githubusercontent.com/705617/197498650-eec3f9a8-d917-448c-96e5-4ae871b5da83.png)

**Comment by rand0mm** [comment]
"По кнопке "построить" отображается единый список всех друзей выбранных пользователей (в виде панелей) Пользователи должны быть отсортированы по фамилии/имени (с отображением пола, возраста, количества друзей и фотографии). При этом цвет панели друга тем ярче, чем у большего числа выбранных пользователей он находится в друзьях."

Я сделал как прочитал) "пользователи" это те кого добавили через поиск "друзья " это их друзья, сортивка и поля есть у пользователей, поправлю. одну минуту))

**Comment by rand0mm** [comment]
Не было свободного времени на этой неделе, залил обнову, вк апи разрешает 3 запроса в секунду, так что запросы синхронные, плюс они ставятся на паузу если мы покидаем главную и возобновляются при возвращении, перезагрузке страницы так же не мешает процессу подкачки
